import "./globals.scss";
import Sidebar from "./components/sidebar";


export const metadata = {
  title: "Next App Template : Sahin",
  description: "Generated by create next app by Sahin Alam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        
        {children}
      </body>
    </html>
  );
}
