import "./globals.scss";
import Animation from "./components/App";

export const metadata = {
  title: "Next App Template : Sahin",
  description: "Generated by create next app by Sahin Alam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Animation />
      </body>
    </html>
  );
}
